# Generated by Django 2.2.4 on 2019-10-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='your_taste_movie',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
