# Generated by Django 2.2.4 on 2019-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190925_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(default=''),
        ),
    ]
