# Generated by Django 2.2.4 on 2019-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190926_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermodel',
            name='cluster_choice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='recommend_movie',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
