# Generated by Django 2.2.4 on 2019-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190926_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommend_user',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
